USE [master]
GO
/****** Object:  Database [SEGRETERIA]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE DATABASE [SEGRETERIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SEGRETIA', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SEGRETIA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SEGRETIA_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SEGRETIA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SEGRETERIA] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SEGRETERIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SEGRETERIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SEGRETERIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SEGRETERIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SEGRETERIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SEGRETERIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [SEGRETERIA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SEGRETERIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SEGRETERIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SEGRETERIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SEGRETERIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SEGRETERIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SEGRETERIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SEGRETERIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SEGRETERIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SEGRETERIA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SEGRETERIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SEGRETERIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SEGRETERIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SEGRETERIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SEGRETERIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SEGRETERIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SEGRETERIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SEGRETERIA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SEGRETERIA] SET  MULTI_USER 
GO
ALTER DATABASE [SEGRETERIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SEGRETERIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SEGRETERIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SEGRETERIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SEGRETERIA] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SEGRETERIA', N'ON'
GO
ALTER DATABASE [SEGRETERIA] SET QUERY_STORE = OFF
GO
USE [SEGRETERIA]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [SEGRETERIA]
GO
/****** Object:  Table [dbo].[ALUNNI]    Script Date: 5/17/2018 11:29:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUNNI](
	[IDAlunno] [bigint] IDENTITY(1,1) NOT NULL,
	[Matricola] [bigint] NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Cognome] [varchar](50) NOT NULL,
	[DataNascita] [date] NOT NULL,
	[AnnoNascita] [numeric](4, 0) NOT NULL,
 CONSTRAINT [PK_ALUNNI] PRIMARY KEY CLUSTERED 
(
	[IDAlunno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CORSILAUREA]    Script Date: 5/17/2018 11:29:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORSILAUREA](
	[IDCorso] [int] NOT NULL,
	[NomeCorso] [varchar](50) NOT NULL,
	[AnnoAccademico] [char](9) NOT NULL,
 CONSTRAINT [PK_CORSILAUREA] PRIMARY KEY CLUSTERED 
(
	[IDCorso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ESAMI]    Script Date: 5/17/2018 11:29:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESAMI](
	[IDEsame] [int] NOT NULL,
	[NomeEsame] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ESAMISOSTENUTI] PRIMARY KEY CLUSTERED 
(
	[IDEsame] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ESAMISOSTENUTI]    Script Date: 5/17/2018 11:29:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESAMISOSTENUTI](
	[Matricola] [bigint] NOT NULL,
	[IDEsame] [int] NOT NULL,
	[Voto] [numeric](2, 0) NOT NULL,
	[Data] [date] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Index [IX_ALUNNI_ANNONASCITA]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_ALUNNI_ANNONASCITA] ON [dbo].[ALUNNI]
(
	[AnnoNascita] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ALUNNI_COGNOME]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_ALUNNI_COGNOME] ON [dbo].[ALUNNI]
(
	[Cognome] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_ALUNNI_MATRICOLA]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_ALUNNI_MATRICOLA] ON [dbo].[ALUNNI]
(
	[Matricola] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_ESAMISOSTENUTI_DATA]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_ESAMISOSTENUTI_DATA] ON [dbo].[ESAMISOSTENUTI]
(
	[Data] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_ESAMISOSTENUTI_MATRICOLA]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_ESAMISOSTENUTI_MATRICOLA] ON [dbo].[ESAMISOSTENUTI]
(
	[Matricola] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_ESAMISOSTENUTI_VOTO]    Script Date: 5/17/2018 11:29:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_ESAMISOSTENUTI_VOTO] ON [dbo].[ESAMISOSTENUTI]
(
	[Voto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SEGRETERIA] SET  READ_WRITE 
GO
